### ISSUE TITLE
不要と思われる一文が記載されている

### ISSUE THREAD

**Issue by ossan-pg** [hitsumabushi845/gas-slack-integration-text#4]
gas_slack_lecture_text.pdf (v1.1) の P.51 に「2019 年冬に私の勤務している株式会社」という一文があります。
文脈を踏まえると恐らく不要な文かと思われます。
![image](https://user-images.githubusercontent.com/7059614/144551960-7b5152b6-d64e-4fae-80b1-df984889c0be.png)

コード上では下記の箇所になると思います。
https://github.com/hitsumabushi845/gas-slack-integration-text/blob/b5a45a95957fa587dcdd951d13ee35e381a210bc/gas_slack_lecture_text.tex#L1389

**Comment by hitsumabushi845** [comment]
@ossan-pg 
ご指摘ありがとうございます。  
修正し、リリースしました。
https://github.com/hitsumabushi845/gas-slack-integration-text/releases/tag/v1.2
